apiVersion: v2
name: k8s-github-action-runner
version: 1.0.0
appVersion: 2.165.2
description: GitHub Actions Runner for Kubernetes
home: https://github.com/mpriscella/k8s-actions
type: application
keywords:
  - github
  - actions
  - self-hosted
  - runner
maintainers:
  - name: mpriscella
    email: mpriscella@gmail.com
