name: Lint Helm Chart

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run linter
        id: lint
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: lint
